apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lorcana-proxy-print
  namespace: lorcana-proxy
  labels:
    app: lorcana-proxy-print
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - lorcana-proxy.example.com
    secretName: lorcana-proxy-tls
  rules:
  - host: lorcana-proxy.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lorcana-proxy-print
            port:
              number: 80
