apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lorcana-proxy-print
  namespace: argocd
  labels:
    app.kubernetes.io/name: lorcana-proxy-print
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/alscec/Lorcana_Proxy_Print.git
    targetRevision: main
    path: k8s
    
  destination:
    server: https://kubernetes.default.svc
    namespace: lorcana-proxy
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        
  revisionHistoryLimit: 10
  
  # Health assessment
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
